// Mello Programming Language
// Copyright (C) 2026 Mohammed Tamer Mohammed Ahmed El-Azab. All Rights Reserved.
//
// This source code is private and protected by intellectual property laws.
// Unauthorized use, modification, or distribution for any competitive 
// academic or commercial purpose is strictly prohibited without 
// explicit written permission from the author.

#include "lexer.hpp"
#include "parser.hpp"
#include "arduino_utils.hpp"

int main(int argc, char* argv[]) {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);

    std::string fileName;

    if (argc > 1) {
        fileName = argv[1];
    }

    if (fileName.empty()) {
        std::cout << "Enter the Mello file name: ";
        std::cin >> fileName;
    }

    std::ifstream file(fileName);
    if (!file.is_open()) {
        std::cerr << "Error: Could not open file " << fileName << std::endl;
        return 1;
    }

    std::string sourceCode((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    file.close();

    Lexer lexer(sourceCode);
    std::vector<Token> tokens = lexer.tokenize();

    Parser parser(tokens);
    std::vector<std::unique_ptr<ASTNode>> program = parser.parse();
    
    std::filesystem::path sketchDir = getTempSketchDir();
    std::filesystem::create_directories(sketchDir);
    std::filesystem::path inoFilePath = sketchDir / "output.ino";

    std::ofstream outputFile(inoFilePath.string());
    if (!outputFile.is_open()) {
        std::cerr << "Error: Could not open output file." << std::endl;
        return 1;
    }

    bool hasSetup = false;
    bool hasLoop = false;
    bool hasSerial = false;
    bool hasSerialCommand = false;

    std::string includesCode = "";
    std::string globalVariablesCode = "";
    std::string functionsCode = "";
    std::string author = "// Generated by Mello Programming Language\n"
                         "// Copyright (C) 2026 Mohammed Tamer Mohammed Ahmed El-Azab. All Rights Reserved.\n"
                         "//\n"
                         "// This source code is private and protected by intellectual property laws\n"
                         "// Unauthorized use, modification, or distribution for any competitive\n"
                         "// academic or commercial purpose is strictly prohibited without\n"
                         "// explicit written permission from the author";

    for (const auto& node : program) {
        if (auto varNode = dynamic_cast<VarAssignNode*>(node.get())) {
            std::string code = varNode->toCpp();

            if (code.find(varNode->name + " =") == 0) {
                std::cerr << "\nSyntax Error: You cannot reassign the variable '" 
                          << varNode->name << "' outside of a function.\n"
                          << "Please move '" << varNode->name << " = ...' inside 'func start():' or 'func loop():'.\n" 
                          << std::endl;
                
                outputFile.close();
                
                std::filesystem::remove_all(sketchDir);

                return EXIT_FAILURE; 
            } else {
                globalVariablesCode += code;
            }
        } else {
            std::string code = node->toCpp();
            
            if (code.find("void setup()") != std::string::npos) {
                hasSetup = true;
            }

            if ((code.find("Serial.print") != std::string::npos) || (code.find("Serial.println") != std::string::npos) || (code.find("Serial.available") != std::string::npos) || (code.find("Serial.read") != std::string::npos)) {
                hasSerialCommand = true;
            }

            if (code.find("Serial.begin") != std::string::npos) {
                hasSerial = true;
            }

            if (code.find("void loop()") != std::string::npos) {
                hasLoop = true;
            }
            
            functionsCode += code + "\n";
        }
    }

    if (!includedLibraries.empty()) {
        for (const auto& lib : includedLibraries) {
            includesCode += "#include <" + lib + ".h>\n";
        }
    }

    outputFile << author << "\n";
    outputFile << includesCode << "\n";
    outputFile << globalVariablesCode << "\n";

    if (!hasSetup) {
        std::vector<std::unique_ptr<ASTNode>> setupBody;

        if (!hasSerial && hasSerialCommand) {
            std::vector<std::unique_ptr<ExpressionNode>> beginArgs;

            beginArgs.push_back(std::make_unique<LiteralNode>(Token(TokenType::NUMBER, "9600")));
            setupBody.push_back(std::make_unique<FunctionCallNode>("Serial.begin", std::move(beginArgs)));
        }

        FunctionNode autoSetup("setup", std::move(setupBody));
        outputFile << autoSetup.toCpp() << "\n";

    } else if (!hasSerial && hasSerialCommand) {
        size_t pos = functionsCode.find("void setup() {");

        if (pos != std::string::npos) {
            size_t insertPos = functionsCode.find('\n', pos) + 1;
            functionsCode.insert(insertPos, "Serial.begin(9600);\n");
        }
    }

    outputFile << functionsCode << "\n";

    if (!hasLoop) {
        FunctionNode autoLoop("loop", {});
        outputFile << autoLoop.toCpp();
    }

    outputFile.close();

    if (!std::filesystem::exists(ARDUINO_CLI_PATH)) {
        std::cerr << "Error: arduino-cli.exe not found at the specified path!" << std::endl;
        return EXIT_FAILURE;
    }

    if (std::filesystem::exists(CLANG_FORMAT_PATH)) {
        std::string formatCommand = CLANG_FORMAT_PATH + " --style=Google -i \"" + inoFilePath.string() + "\"";
        std::system(formatCommand.c_str());
    } else {
        std::cerr << "Warning: clang-format not found locally, skipping formatting." << std::endl;
    }

    // Delete when u finish from here

    std::string sketchCode;

    std::ifstream sketchCodeFile(inoFilePath.string());

    if (sketchCodeFile.is_open()) {
        while (getline(sketchCodeFile, sketchCode)) {
            std::cout << sketchCode << std::endl;
        }
    } else {
        std::cerr << "Warning: Cann't open the sketch code file." << std::endl;
    }

    sketchCodeFile.close();

    // to here

    installLibraries();

    bool compiledSuccessfully = compileCode();

    if (compiledSuccessfully && argc >= 3 && std::string(argv[2]) == "--upload") {
        uploadCode();
    }

    std::filesystem::remove_all(sketchDir);

    return EXIT_SUCCESS;
}